name: CD Staging (AKS)

on:
  workflow_run:
    workflows: ["CI Build & Test & Push to ACR"]
    types: [completed]

env:
  RG_NAME: deakinuni
  AKS_NAME: kaustubhweek10aks

jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (manifests)
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS credentials (staging)
        run: az aks get-credentials --resource-group $RG_NAME --name $AKS_NAME --overwrite-existing

      - name: Set image tags from CI SHA
        run: |
          SHA=${{ github.event.workflow_run.head_sha }}
          for f in k8s/*.yaml; do
            sed -i "s#:latest#:${SHA}#g" "$f"
          done

      - name: Apply K8s manifests (staging)
        run: kubectl apply -f k8s/
