# Triggering comment
name: CI Build & Test & Push to ACR

on:
  push:
    branches:
      - testing

env:
  ACR_NAME: kaustubhweek10acr
  ACR_LOGIN_SERVER: kaustubhweek10acr.azurecr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - frontend
          - backend/product_service
          - backend/order_service
          - backend/customer_service

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Only needed for Python service unit-tests; skip for frontend
      - name: Set up Python
        if: ${{ matrix.service != 'frontend' }}
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install deps & run tests (backend services)
        if: ${{ matrix.service != 'frontend' }}
        run: |
          cd ${{ matrix.service }}
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -d tests ]; then python -m unittest discover -v || true; fi

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR login
        run: az acr login --name $ACR_NAME

      - name: Build & push image
        run: |
          IMAGE_NAME=$(basename "${{ matrix.service }}") # e.g., product_service
          IMAGE_TAG=$ACR_LOGIN_SERVER/${IMAGE_NAME}:${{ github.sha }}
          docker build -t "$IMAGE_TAG" ${{ matrix.service }}
          docker push "$IMAGE_TAG"
      - name: Tag 'latest' too (optional)
        run: |
          IMAGE_NAME=$(basename "${{ matrix.service }}")
          docker tag $ACR_LOGIN_SERVER/${IMAGE_NAME}:${{ github.sha }} $ACR_LOGIN_SERVER/${IMAGE_NAME}:latest
          docker push $ACR_LOGIN_SERVER/${IMAGE_NAME}:latest
